baseurl = "http://docs.getcloudify.org/"
languageCode = "en-us"
title = "Cloudify Documentation"
theme="hugo-bootswatch"
uglyurls=false

[blackfriday]
plainIdAnchors=true

[params]
highlightStyle="darkula"
projecturl="https://github.com/cloudify-cosmo/docs.getcloudify.org"
projectversion="master"
# this is where you type google analytics ID
googleAnalytics="UA-31930048-1"
# this is where you decide where "/" redirects to
homepage="/intro/what-is-cloudify/"

# this is where you control the top menu
[[menu.main]]
    name = "docs"
    weight = -100
    [[menu.main]]
        name = "3.4.2 (Latest GA)"
        parent = "docs"
        weight = 9
        url = "http://docs.getcloudify.org/3.4.2/"
    [[menu.main]]
        name = "3.4.1"
        parent = "docs"
        weight = 10
        url = "http://docs.getcloudify.org/3.4.1/"
    [[menu.main]]
        name = "3.4.0"
        parent = "docs"
        weight = 11
        url = "http://docs.getcloudify.org/3.4.0/"
    [[menu.main]]
        name = "4.0.0 (Early Access)"
        parent = "docs"
        weight = 12
        url = "http://docs.getcloudify.org/4.0.0/"
    [[menu.main]]
        name = "3.3.1"
        parent = "docs"
        weight = 20
        url = "http://docs.getcloudify.org/3.3.1/"
    [[menu.main]]
        name = "3.3.0"
        parent = "docs"
        weight = 30
        url = "http://docs.getcloudify.org/3.3.0/"
    [[menu.main]]
        name = "3.2"
        parent = "docs"
        weight = 40
        url = "http://getcloudify.org/guide/3.2/"

    [[menu.main]]
        name = "tutorials"
        weight = -90
        url = "http://getcloudify.org/cloudifysourcetv.html"

    [[menu.main]]
        name = "training"
        weight = -80
        url = "http://getcloudify.org/participate.htm"

    [[menu.main]]
        name = "resources"
        weight = -70
        
    [[menu.main]]
        name = "examples catalog"
        parent = "resources"
        weight = 0
        url = "http://getcloudify.org/examples/home.html"
    [[menu.main]]
        name = "mailing list"
        parent = "resources"
        weight = 1
        url = "https://groups.google.com/forum/#!forum/cloudify-users"
    [[menu.main]]
        name = "blog"
        parent = "resources"
        weight = 2
        url = "http://getcloudify.org/blog/"


# this is where you control the order of sections in docs
# 'identifier' must match the section's directory name
# 'name' is how you want to display the section on screen
# 'weight' sets the order of sections in docs (smaller is higher)
[[menu.docs]]
    identifier = "intro"
    name = "Introduction"
    url = "/intro/what-is-cloudify"
    weight = 0

[[menu.docs]]
  identifier = "installation"
  name = "Installation"
  weight = 1

[[menu.docs]]
  identifier = "cli"
  name = "Command Line Interface"
  weight = 2

[[menu.docs]]
  identifier = "blueprints"
  name = "Blueprints"
  weight = 3

[[menu.docs]]
  identifier = "plugins"
  name = "Plugins"
  weight = 4

[[menu.docs]]
  identifier = "workflows"
  name = "Workflows"
  weight = 5

[[menu.docs]]
  identifier = "manager"
  name = "Cloudify Manager"
  weight = 6

[[menu.docs]]
  identifier = "manager_architecture"
  name = "Manager Architecture"
  weight = 7


[[menu.docs]]
  identifier = "manager_webui"
  name = "Manager Web Interface"
  weight = 8

[[menu.docs]]
  identifier = "manager_policies"
  name = "Manager Policies"
  weight = 9


[[menu.docs]]
  identifier = "agents"
  name = "Agents"
  weight = 10


[[menu.docs]]
  identifier = "composer"
  name = "Blueprint Composer"
  weight = 11

[[menu.docs]]
  identifier = "apis"
  name = "APIs"
  weight = 12
