baseurl = "http://docs.getcloudify.org/"
languageCode = "en-us"
title = "Cloudify Documentation"
theme="hugo-redlounge"
uglyurls=true

[blackfriday]
plainIdAnchors=true

[permalinks]
    guide= "/3.3.0/:filename"

[params]
categoriescss= "/style/template.css"
highlightStyle="darkula"

sidebartitle = "Menu"
sidebartagline = "Is super awesome"

projecturl="https://github.com/cloudify-cosmo/docs.getcloudify.org"
projectversion="master"


[[menu.main]]
    name = "Blog"
    url = "/posts"

[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/CloudifySource"
    identifier = "twitter"

[[menu.footer]]
    name = "Blog"
    url = "/posts"
